# action.yml
name: 'Checkov Github Action'
author: 'Chris Mavrakis'
description: 'Run Checkov against Terraform/CloudFormation infrastructure code, as a pre-packaged Github Action.'
inputs:
  directory:
    description: 'directory with infrastructure code to scan'
    default: '.'
branding:
  icon: 'shield'
  color: 'purple'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.directory }}
