# action.yml
name: 'Checkov Github Action'
author: 'Chris Mavrakis'
description: 'Run Checkov against Terraform/CloudFormation infrastructure code, as a pre-packaged Github Action.'
inputs:
  directory:
    description: 'directory with infrastructure code to scan'
    default: '.'
    required: false
  check:
    description: 'Run scan only on a specific check identifier (comma separated)'
    required: false
  skip_check:
    description: 'Run scan on all checks but a specific check identifier (comma separated)'
    required: false
  quiet:
    description: 'display only failed checks'
    required: false
  framework:
    description: 'run only on a specific infrastructure'
    required: false
branding:
  icon: 'shield'
  color: 'purple'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.directory }}
    - ${{ inputs.check }}
    - ${{ inputs.skip_check }}
    - ${{ inputs.quiet }}
