name: Bump Node Version
branding:
  icon: package
  color: green
description: Bumps Node version and creates a pull request.
inputs:
  git-user-email:
    description: Git user.email to use for the commit.
    default: 41898282+github-actions[bot]@users.noreply.github.com
  git-user-name:
    description: Git user.name to use for the commit.
    default: github-actions[bot]
  package-manager:
    description: Set to 'yarn' to use yarn. Defaults to npm.
    default: npm
  version-type:
    description: Bumps the package version based on value (e.g. patch)
    default: patch
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.git-user-name }}
    - ${{ inputs.git-user-email }}
    - ${{ inputs.package-manager }}
    - ${{ inputs.version-type }}
