name: "Hugo Build"
description: "Hugo as an action, with extended support and legacy versions"
author: jakejarvis
runs:
  using: docker
  image: docker://ghcr.io/jakejarvis/hugo-extended:0.104.0
branding:
  icon: edit
  color: gray-dark
