name: Node Update Dependencies
description: Updates npm dependencies, bumps patch version, and creates a pull request with the changes.
inputs:
  git-user-email:
    description: Git user.email to use for the commit.
    default: gh-action-node-update-deps@example.com
  git-user-name:
    description: Git user.name to use for the commit.
    default: gh-action-node-update-deps
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.git-user-name }}
    - ${{ inputs.git-user-email }}
