name: build
on: repository_dispatch

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch release version
        run: |
          checkov_version=$(curl -sL https://api.github.com/repos/bridgecrewio/checkov/tags | jq -r '.[0]["name"]' )
          echo "checkov=='$checkov_version'" > 'requirements.txt'
          echo "version = '$checkov_version'"
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git commit -am "update checkov version to '$checkov_version'"
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "latest tag: $latest_tag"
          new_tag=$(echo $latest_tag | awk -F. -v a="$1" -v b="$2" -v c="$3" '{printf("%d.%d.%d", $1+a, $2+b , $3+1)}')
          git tag $new_tag
          git push origin $new_tag

