name: build
on: repository_dispatch

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch release version
        run: |
          checkov_version=$(curl -sL https://api.github.com/repos/bridgecrewio/checkov/tags | jq -r '.[0]["name"]' )
          echo "checkov=='$checkov_version'" > 'requirements.txt'
          echo "version = '$checkov_version'"
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git commit -am "New release version"
          new_tag=$checkov_version
          git tag $new_tag
          git push origin $new_tag

