name: Build example site

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Checkout gohugoio/hugoBasicExample
      uses: actions/checkout@master
      with:
        repository: gohugoio/hugoBasicExample
        path: example/
        fetch-depth: 1
    - name: Build site
      uses: ./
      with:
        args: --source example/ --minify --enableGitInfo --verbose
